### PR TITLE
Merge cs-studio fork back into the main repo

### PR DESCRIPTION
**Pull request by shroffk**

### CODE REVIEW

**Comment by berryma4** [comment]
Maybe we can help people add a git pre commit hook?

**Comment by willrogers** [comment]
I was just playing: on the cs-studio build if we change the whitespace violations to errors not warnings the travis build should fail.  And any maven build.

**Comment by willrogers** [comment]
Our Jenkins jobs are the general ones and I've got the checkstyle graphs up.

Your Jenkins jobs are the special Maven ones and I never could figure out how to show the checkstyle graphs.
checkstyle

**Comment by berryma4** [comment]
A git pre commit hook would keep the commits from even happening though.
http://www.rubydoc.info/gems/java-checkstyle/1.0.0

**Comment by berryma4** [comment]
I should remark I like having the build fail on checkstlye, I would like to add the pre commit hook too.

**Comment by willrogers** [comment]
The pre-commit hook is nice.  The problem is that it relies on everyone to set them up themselves, and they just might not.

I mean, the people who bother to set up the commit hook are probably the people who already have whitespace highlighted in their IDE...

**Comment by shroffk** [comment]
sorry for the trouble

**Comment by shroffk** [comment]
@berryma4 @willrogers @utzeln @claudio-rosati @kasemir 
should I go ahead and merge this?

Next will be the VImage branch

**Comment by claudio-rosati** [comment]
OK for me

**Comment by willrogers** [comment]
Yes, ok for me.

**Comment by kasemir** [comment]
Does this mean we then delete ControlSystemStudio/diirt and change our build setups to pull diirt from the diirt repo?
Does it leave CS-Studio as the primary user of diirt and we remain in control of changes, or could diirt changes then impact the build stability of CS-Studio?

The alternative would be: Ignore diirt/diirt, and instead continue with CS-Studio/diirt

**Comment by shroffk** [comment]
Well continuing is painful too...diirt/diirt is setup to release to mavencenteral, etc...also having 2 is a pain (Issue ticket are still created here but then resolved on the fork)
We will update the build jobs to point to this repo and then delete the cs-studio one.
The CI will ensure stability, PR will have to be tested before merged.

**Comment by kasemir** [comment]
OK then, go ahead.

**Pull request merged**
