### PR TITLE
Issue 79

### PR DESCRIPTION
**Pull request by css-iter**
Time-stamp format pattern can be read from settings.xml. Changes also from Local to ZonedDateTime as format can also include zone. Tests changed to reflect this.

### CODE REVIEW

**Comment by shroffk** [comment]
Hi, 
Would it be possible for you to squash the merge commits and create a PR?

**Comment by boryto** [comment]
Hi, changed. Ok now?

**Comment by shroffk** [comment]
Great, I think this is ready...
I am just trying to get travis and CI all set up for PR's

**Comment by shroffk** [comment]
One final request, could you rebase your branch ```css-iter:issue_79``` on the master ```diirt:master```.
That way you will get the newly created .travis.yml file and this PR will have CI test results with it. (since I don't have access to the iter fork I wasn't able to do this for you)

Thanks for your patience, but this is quite useful it getting this whole project set up properly for future PR's

**Pull request merged**
